In [1]:
from datascience import *

In [9]:
pokemon_i_like = make_array('Pikachu', 'Charizard', 'Squirtle')

In [3]:
pokemon_i_like

array(['Pikachu', 'Charizard', 'Squirtle'],
      dtype='<U9')

In [43]:
len(pokemon_i_like)

3

In [10]:
pokemon_i_like.item(0)

'Pikachu'

In [11]:
pokemon_i_like.item(1)

'Charizard'

In [16]:
temps_f = make_array(100, 78, 32, -40)

In [17]:
temps_f * 2

array([200, 156,  64, -80])

In [7]:
temps_f.size

4

In [8]:
temps_f.sum()

170

In [9]:
temps_f.mean()

42.5

In [6]:
sorted(temps_f)

[-40, 32, 78, 100]

In [20]:
import numpy as np

In [11]:
np.diff(temps_f)

array([-22, -46, -72])

In [18]:
temps_c = (temps_f - 32) * (5/9)
temps_c

array([ 37.77777778,  25.55555556,   0.        , -40.        ])

In [22]:
np.round(temps_c, 2)

array([ 37.78,  25.56,   0.  , -40.  ])

In [1]:
True + False + True

2

In [12]:
np.count_nonzero(make_array(1 < 2, 2 < 1, 8 < 7, 42 < 43))

2

In [13]:
np.char.upper(pokemon_i_like)

array(['PIKACHU', 'CHARIZARD', 'SQUIRTLE'],
      dtype='<U9')

In [14]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(5, 101, 5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [24]:
np.arange(13, 11.9, -0.1)

array([ 13. ,  12.9,  12.8,  12.7,  12.6,  12.5,  12.4,  12.3,  12.2,
        12.1,  12. ])

In [21]:
16.9

16.9

---

In [26]:
pos_denoms = np.arange(1, 9998, 4)
pos_denoms

array([   1,    5,    9, ..., 9989, 9993, 9997])

In [29]:
# crushed ice?
neg_denoms = np.arange(3, 10000, 4)
neg_denoms

array([   3,    7,   11, ..., 9991, 9995, 9999])

In [30]:
pos_terms = 1 / pos_denoms
neg_terms = 1/ neg_denoms

In [31]:
pos_terms

array([  1.00000000e+00,   2.00000000e-01,   1.11111111e-01, ...,
         1.00110121e-04,   1.00070049e-04,   1.00030009e-04])

In [34]:
4 * (sum(pos_terms) - sum(neg_terms))

3.1413926535917955

---

In [36]:
pokemon = Table.read_table('data/pokemon.csv')

In [37]:
pokemon.column('name')

array(['Bulbasaur', 'Ivysaur', 'Venusaur', 'Charmander', 'Charmeleon',
       'Charizard', 'Squirtle', 'Wartortle', 'Blastoise', 'Caterpie',
       'Metapod', 'Butterfree', 'Weedle', 'Kakuna', 'Beedrill', 'Pidgey',
       'Pidgeotto', 'Pidgeot', 'Rattata', 'Raticate', 'Spearow', 'Fearow',
       'Ekans', 'Arbok', 'Pikachu', 'Raichu', 'Sandshrew', 'Sandslash',
       'Nidoran♀', 'Nidorina', 'Nidoqueen', 'Nidoran♂', 'Nidorino',
       'Nidoking', 'Clefairy', 'Clefable', 'Vulpix', 'Ninetales',
       'Jigglypuff', 'Wigglytuff', 'Zubat', 'Golbat', 'Oddish', 'Gloom',
       'Vileplume', 'Paras', 'Parasect', 'Venonat', 'Venomoth', 'Diglett',
       'Dugtrio', 'Meowth', 'Persian', 'Psyduck', 'Golduck', 'Mankey',
       'Primeape', 'Growlithe', 'Arcanine', 'Poliwag', 'Poliwhirl',
       'Poliwrath', 'Abra', 'Kadabra', 'Alakazam', 'Machop', 'Machoke',
       'Machamp', 'Bellsprout', 'Weepinbell', 'Victreebel', 'Tentacool',
       'Tentacruel', 'Geodude', 'Graveler', 'Golem', 'Ponyta', 'Rapidash

In [39]:
# crushed ice: get the attack
attacks = pokemon.column('attack')
attacks

array([ 49,  62, 100,  52,  64, 104,  48,  63, 103,  30,  20,  45,  35,
        25, 150,  45,  60,  80,  56,  71,  60,  90,  60,  95,  55,  85,
        75, 100,  47,  62,  92,  57,  72, 102,  45,  70,  41,  67,  45,
        70,  45,  80,  50,  65,  80,  70,  95,  55,  65,  55, 100,  35,
        60,  52,  82,  80, 105,  70, 110,  50,  65,  95,  20,  35,  50,
        80, 100, 130,  75,  90, 105,  40,  70,  80,  95, 120,  85, 100,
        65,  75,  35,  60,  90,  85, 110,  45,  70,  80, 105,  65,  95,
        35,  50,  65,  45,  48,  73, 105, 130,  30,  50,  40, 105,  50,
        80, 120, 105,  55,  65,  90,  85, 130,   5,  55, 125,  40,  65,
        67,  92,  45,  75,  45, 110,  50,  83,  95, 155, 100,  10, 155,
        85,  48,  55,  65,  65, 130,  60,  40,  60,  80, 115, 135, 110,
        85,  90, 100,  64,  84, 134, 150, 100,  49,  62,  82,  52,  64,
        84,  65,  80, 105,  46,  76,  30,  50,  20,  35,  60,  90,  90,
        38,  58,  40,  25,  30,  20,  40,  50,  75,  40,  55,  9

In [42]:
np.average(attacks)

77.857677902621717

# Miscellaneous things Lawton needs to teach you

In [14]:
'and'.join(make_array('1', '2', '3')) # the sequence has to be strs

'1and2and3'